.code
	xor r0, r0, r0
	addi r12, r0, 0
	shiftli r12, 12
	addi r12, r0, 0
	shftli r12, 12
	addi r12, r0, 0
	shftli r12, 12
	addi r12, r0, 3
	shftli r12, 4
	addi r12, r0, 2166
	shftli r12, 4
	addi r12, r0, 4
	xor r0, r0, r0
	addi r3, r0, 0
	shiftli r3, 12
	addi r3, r0, 0
	shftli r3, 12
	addi r3, r0, 0
	shftli r3, 12
	addi r3, r0, 29
	shftli r3, 4
	addi r3, r0, 1739
	shftli r3, 4
	addi r3, r0, 6
	ld r1, 4144
	ld r14, 4200
	addi r4, 98
