.code
	xor r0, r0, r0
	xor r5, r5, r5
	addi r5, 0
	shftli r5, 12
	addi r5, 0
	shftli r5, 12
	addi r5, 0
	shftli r5, 12
	addi r5, 0
	shftli r5, 12
	addi r5, 259
	shftli r5, 4
	addi r5, 8
	br r5
	priv r3, r4, r0, 3
	subi r31, 8
	mov (r31)(0), r1
	mov r1, (r31)(0)
	addi r31, 8
	xor r1, r1, r1
	addi r1, 4095
	shftli r1, 12
	addi r1, 4095
	shftli r1, 12
	addi r1, 4095
	shftli r1, 12
	addi r1, 4095
	shftli r1, 12
	addi r1, 4095
	shftli r1, 4
	addi r1, 15
